# Generated by Django 5.0 on 2024-01-03 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FileField(default=django.utils.timezone.now, upload_to='products/price/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
