# Generated by Django 5.0 on 2024-01-04 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='price_info',
            field=models.FileField(default=django.utils.timezone.now, upload_to='products/price/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
